swagger: '2.0'
info:
  version: '0.1.2'
  title: Time To Fish
host: localhost:3010
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /menus:
    x-swagger-router-controller: menus.server.controller
    get:
      operationId: getAll
      summary: 'Returns all menu items, sorted by: key, parent->child, sequence, name (alphabetical)'
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/GetMenuItemsResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
  /swagger:
    x-swagger-pipe: swagger_raw
# complex object schema definitions
definitions:
  MenuItem:
    required:
      - key
      - name
      - sequence
    properties:
      key:
        type: string
      name:
        type: string
      sequence:
        type: integer
        format: int32
      description:
        type: string
      parent:
        $ref: '#/definitions/MenuItem'
      state:
        type: string
      permissions:
        type: array
        items:
          type: string
          format: hex
  GetMenuItemsResponse:
    required:
      - menuItems
    properties:
      menuItems:
        type: array
        items:
          $ref: '#/definitions/MenuItem'
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string