swagger: '2.0'
info:
  version: '0.0.1'
  title: Time To Fish
host: localhost:3010
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /menus:
    x-swagger-router-controller: menu-item.server.controller
    get:
      summary: Returns the user's menu
      operationId: getUserMenu
      parameters:
        - name: ownerState
          in: query
          description: menu item key
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/GetUserMenuResponse'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
# complex object schema definitions
definitions:
  GetUserMenuResponse:
    required:
      - menuItems
    properties:
      menuItems:
        type: array
        items:
          type: object
          properties:
            menuId:
              type: number
            permissionsRequired:
              type: string
            name:
              type: object
              properties:
                state:
                  type: string
                display:
                  type: string
            owner:
              type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string